# Generated by Django 4.1.4 on 2023-01-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_author_categoryn_post_postcategory_post_postcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='simpleapp.PostCategory', to='simpleapp.categoryn'),
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='categoryThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simpleapp.categoryn'),
        ),
    ]
