# Generated by Django 4.1.4 on 2023-01-19 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpleapp', '0003_alter_post_postcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryn',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
